"""empty message

Revision ID: 5b41fdc375d8
Revises: f44efc3fefa1
Create Date: 2023-11-30 09:22:40.798704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b41fdc375d8'
down_revision = 'f44efc3fefa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packagings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pallet_avion', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('peso_neto_pallet_avion', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packagings', schema=None) as batch_op:
        batch_op.drop_column('peso_neto_pallet_avion')
        batch_op.drop_column('pallet_avion')

    # ### end Alembic commands ###
