"""empty message

Revision ID: 5b514ba6439e
Revises: edb39c5c3f75
Create Date: 2023-11-28 10:45:40.358281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b514ba6439e'
down_revision = 'edb39c5c3f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packagings', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_packagings_producto_id', 'productos', ['producto_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packagings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_packagings_producto_id', type_='foreignkey')

    # ### end Alembic commands ###
