"""empty message

Revision ID: edb39c5c3f75
Revises: 70e7b7a224f1
Create Date: 2023-11-28 09:54:06.234750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb39c5c3f75'
down_revision = '70e7b7a224f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packagings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('categoria_nombreesp', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('producto_nombreesp', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('fk_packagings_producto_id', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packagings', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_packagings_producto_id', 'productos', ['producto_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('producto_nombreesp')
        batch_op.drop_column('categoria_nombreesp')
        batch_op.drop_column('categoria_id')

    # ### end Alembic commands ###
