"""empty message

Revision ID: f44efc3fefa1
Revises: 
Create Date: 2023-11-30 07:41:25.956325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44efc3fefa1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreesp', sa.String(length=80), nullable=False),
    sa.Column('nombreeng', sa.String(length=80), nullable=False),
    sa.Column('foto', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=11), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('isAdmin', sa.String(length=10), nullable=False),
    sa.Column('foto', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreesp', sa.String(length=80), nullable=False),
    sa.Column('nombreeng', sa.String(length=80), nullable=False),
    sa.Column('descripcionesp', sa.Text(), nullable=False),
    sa.Column('descripcioneng', sa.Text(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('foto', sa.String(length=120), nullable=False),
    sa.Column('foto2', sa.String(length=120), nullable=True),
    sa.Column('meses_produccion', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packagings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreesp', sa.String(length=80), nullable=False),
    sa.Column('nombreeng', sa.String(length=80), nullable=False),
    sa.Column('marca', sa.String(length=80), nullable=False),
    sa.Column('presentacion', sa.String(length=80), nullable=False),
    sa.Column('calibre', sa.String(length=80), nullable=False),
    sa.Column('peso_presentacion_g', sa.String(length=80), nullable=False),
    sa.Column('peso_neto_kg', sa.String(length=80), nullable=False),
    sa.Column('tamano_caja', sa.String(length=80), nullable=False),
    sa.Column('pallet_80x120', sa.String(length=80), nullable=False),
    sa.Column('peso_neto_pallet_80x120_kg', sa.String(length=80), nullable=False),
    sa.Column('pallet_100x120', sa.String(length=80), nullable=False),
    sa.Column('peso_neto_pallet_100x120_kg', sa.String(length=80), nullable=False),
    sa.Column('foto', sa.String(length=120), nullable=False),
    sa.Column('foto2', sa.String(length=120), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('categoria_nombreesp', sa.String(length=80), nullable=False),
    sa.Column('producto_nombreesp', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name='fk_packagings_producto_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_packagings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('packaging_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['packaging_id'], ['packagings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'packaging_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_packagings')
    op.drop_table('packagings')
    op.drop_table('productos')
    op.drop_table('users')
    op.drop_table('categorias')
    # ### end Alembic commands ###
