"""empty message

Revision ID: fdff90bf957d
Revises: c9446c3be100
Create Date: 2023-11-23 18:12:42.672356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdff90bf957d'
down_revision = 'c9446c3be100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packagings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto2', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packagings', schema=None) as batch_op:
        batch_op.drop_column('foto2')

    # ### end Alembic commands ###
