"""empty message

Revision ID: 28d11a8be33b
Revises: 9453773f3ff7
Create Date: 2023-11-30 18:27:22.843314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d11a8be33b'
down_revision = '9453773f3ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('foto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
