"""empty message

Revision ID: aa0cddbe2a6a
Revises: 28d11a8be33b
Create Date: 2023-11-30 18:43:37.500687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0cddbe2a6a'
down_revision = '28d11a8be33b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_packagings', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=150),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    with op.batch_alter_table('user_packagings', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###
